<?php

namespace Database\Seeders;

use App\Models\User;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DatabaseSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Limpiar las tablas para evitar duplicados
        DB::statement('DELETE FROM inventory_items;');
        DB::statement('DELETE FROM inventory_categories;');

        // 2. Insertar las Categorías oficiales de tu taller
        DB::table('inventory_categories')->insert([
            ['id' => 1, 'name' => 'Equipos de Medición', 'prefix' => 'MED', 'description' => 'Amperímetros, megómetros, niveles láser y analizadores', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 2, 'name' => 'Herramientas Eléctricas', 'prefix' => 'ELEC', 'description' => 'Taladros, esmeriles, sopladores, bombas de vacío y cargadores', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 3, 'name' => 'Infraestructura y Elevación', 'prefix' => 'INF', 'description' => 'Escaleras de tijera, telescópicas y plegables', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 4, 'name' => 'Conexiones y Tuberías', 'prefix' => 'TUB', 'description' => 'Tubos PVC, codos, curvas, abrazaderas y adaptadores de almacén', 'created_at' => now(), 'updated_at' => now()],
            ['id' => 5, 'name' => 'Insumos y Lubricantes', 'prefix' => 'INS', 'description' => 'Aceites lubricantes, líquidos de limpieza y consumibles', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // 3. Insertar la Data del Inventario mapeando los campos correctos a tus columnas
        // Nota: Asegúrate de que los nombres de las columnas coincidan con tu migración (ej. 'category_id', 'code', 'product', etc.)
        DB::table('inventory_items')->insert([
            // 🧪 CATEGORÍA 1: Equipos de Medición
            ['category_id' => 1, 'code' => 'AMPMTR-01', 'product' => 'Amperímetro', 'brand' => 'CPS', 'description' => 'AC750', 'serial_number' => 'MBIH80040', 'condition' => 'MALOGRADO', 'notes' => 'no tiene sus cabelcitos, no funciona', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'AMPMTR-02', 'product' => 'Amperímetro', 'brand' => 'CPS', 'description' => 'AC750', 'serial_number' => 'MBH046794', 'condition' => 'MALOGRADO', 'notes' => 'no funciona el orificio negro', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'AMPMTR-03', 'product' => 'Amperímetro', 'brand' => 'CPS', 'description' => 'AC750', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'AMPMTR-04', 'product' => 'Amperímetro', 'brand' => 'Phoenix', 'description' => 'DL389 TRMS', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'AMPMTR-05', 'product' => 'Amperímetro', 'brand' => 'FLUKE', 'description' => '302+', 'serial_number' => '66211326MV', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'AMPMTR-06', 'product' => 'Amperímetro', 'brand' => 'FLUKE', 'description' => '302+', 'serial_number' => '65451023MVa', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'AMPMTR-07', 'product' => 'Amperímetro', 'brand' => 'FLUKE', 'description' => '902FC', 'serial_number' => '59900789MV', 'condition' => 'BUENO', 'notes' => 'tiene accesorios', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'MEGMTR-01', 'product' => 'Megómetro', 'brand' => 'FLUKE', 'description' => '1587 FC', 'serial_number' => '60270038', 'condition' => 'BUENO', 'notes' => '02 cable, 02 pinzas, 01 cable tester, 01 voltimetro, 01 cable', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'NVLL-MLT', 'product' => 'Nivel laser', 'brand' => 'BOSCH', 'description' => 'GCL 2-15 G - 3 x 1.5v green laser', 'serial_number' => '803000969 03/2018', 'condition' => 'BUENO', 'notes' => 'maletín con 4 accesorios (803009964)', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'MNMTRO-01', 'product' => 'Manómetro de refrigeración', 'brand' => 'MASTERCOOL', 'description' => null, 'serial_number' => null, 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'MNMTRO-02', 'product' => 'Manómetro de refrigeración', 'brand' => 'MASTERCOOL', 'description' => null, 'serial_number' => null, 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'MNMTRO-03', 'product' => 'Manómetro de refrigeración', 'brand' => 'UNIWELD', 'description' => null, 'serial_number' => null, 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'MNMTRO-04', 'product' => 'Manómetro de refrigeración', 'brand' => 'UNIWELD', 'description' => null, 'serial_number' => null, 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'MNMTRO-05', 'product' => 'Manómetro de refrigeración', 'brand' => 'UNIWELD', 'description' => null, 'serial_number' => null, 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'MNMTRO-06', 'product' => 'Manómetro de refrigeración', 'brand' => 'UNIWELD', 'description' => null, 'serial_number' => null, 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'MNMTRO-07', 'product' => 'Manómetro de refrigeración', 'brand' => 'TESTO', 'description' => '557', 'serial_number' => '48135843', 'condition' => 'BUENO', 'notes' => 'maletín, 3 mangueras, 2 pinzas , 1 acces', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 1, 'code' => 'MNMTRO-08', 'product' => 'Manómetro de refrigeración', 'brand' => 'CPS', 'description' => null, 'serial_number' => '1689173', 'condition' => 'BUENO', 'notes' => 'estuche, 3 mangueras, adaptador r410', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],

            // 🔌 CATEGORÍA 2: Herramientas Eléctricas
            ['category_id' => 2, 'code' => 'BTR-IN-01', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 4,0Ah M-C - inalámbrico 18v, 4.0Ah', 'serial_number' => 'TM36-811160400', 'condition' => 'MALOGRADO', 'notes' => 'No carga y se baja rápido', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-02', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 4,0Ah M-C - inalámbrico 18v, 4.0Ah', 'serial_number' => 'TM38-801270451', 'condition' => 'BUENO', 'notes' => '-', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-03', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 4,0Ah M-C - inalámbrico 18v, 4.0Ah', 'serial_number' => 'TM38-801270438', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-04', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 4,0Ah M-C - inalámbrico 18v, 4.0Ah', 'serial_number' => 'TM38-032280658', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-05', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 4,0Ah M-C - inalámbrico 18v, 4.0Ah', 'serial_number' => 'TM38-032280660', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-06', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 4,0Ah M-C - inalámbrico 18v, 4.0Ah', 'serial_number' => 'WM40-2253000644', 'condition' => 'BUENO', 'notes' => 'Batería de taladro bi turbo', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-07', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 4,0Ah M-C - inalámbrico 18v, 4.0Ah', 'serial_number' => 'WM40-2253000653', 'condition' => 'BUENO', 'notes' => 'Batería de taladro bi turbo', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-08', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 1,5Ah M-A - inalámbrico 18v, 1.5Ah', 'serial_number' => 'TM31-608110857', 'condition' => 'BUENO', 'notes' => 'Batería de taladro pequeño', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-09', 'product' => 'Batería de taladro', 'brand' => 'DEWALT', 'description' => 'DCB204-B3 - 20V, 4.0Ah', 'serial_number' => 'N285517', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-10', 'product' => 'Batería de taladro', 'brand' => 'DEWALT', 'description' => 'DCB204-B3 - 20V, 4.0Ah', 'serial_number' => 'N382276', 'condition' => 'MALOGRADO', 'notes' => 'No carga', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-11', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 6,0Ah M-C - inalámbrico percutor, 18v, 6.0Ah', 'serial_number' => '2607337263', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-12', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 6,0Ah M-C - inalámbrico percutor, 18v, 6.0Ah', 'serial_number' => '2607337263', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-13', 'product' => 'Batería de taladro', 'brand' => 'MAKITA', 'description' => 'BL1830B - soplador, 18V, 3.0Ah', 'serial_number' => '222609JWS', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-14', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 6,0Ah M-C - inalámbrico percutor, 18v, 6.0Ah', 'serial_number' => 'xm35 - 128170865', 'condition' => 'BUENO', 'notes' => 'batería de taladro inalámbrico percutor', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BTR-IN-15', 'product' => 'Batería de taladro', 'brand' => 'BOSCH', 'description' => 'GBA 18V 6,0Ah M-C - inalámbrico percutor, 18v, 6.0Ah', 'serial_number' => 'xm35 - 128171074', 'condition' => 'BUENO', 'notes' => 'batería de taladro inalámbrico percutor', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BMB-VC-01', 'product' => 'Bomba de vacío', 'brand' => 'CPS', 'description' => '220v', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BMB-VC-02', 'product' => 'Bomba de vacío', 'brand' => 'CPS', 'description' => 'VP6D - 220v, 500w, 6cfm, 1/2hp, 10 micras', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BMB-VC-03', 'product' => 'Bomba de vacío', 'brand' => 'CPS', 'description' => 'VP12D - 220v, 700w, 12cfm, 1hp, 25 micras', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'BMB-VC-04', 'product' => 'Bomba de vacío', 'brand' => 'MASTERCOOL', 'description' => '220v, 12cfm, 1hp, 15 micras', 'serial_number' => '1117', 'condition' => 'BUENO', 'notes' => 'su base se cae', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'CGR-BTR-IN-01', 'product' => 'Cargador de batería', 'brand' => 'BOSCH', 'description' => 'GAL 1880 CV - 18V, 8A', 'serial_number' => '001827', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'CGR-BTR-IN-02', 'product' => 'Cargador de batería', 'brand' => 'BOSCH', 'description' => 'GAL 1880 CV - 18V, 8A', 'serial_number' => '000676', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'CGR-BTR-IN-03', 'product' => 'Cargador de batería', 'brand' => 'DEWALT', 'description' => 'DCB115-B2 - 20V, 4A', 'serial_number' => '202148PQ', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'CGR-BTR-IN-04', 'product' => 'Cargador de batería', 'brand' => 'BOSCH', 'description' => 'GAL 1880 CV - 18V, 6A', 'serial_number' => '2607225921', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'CGR-BTR-05', 'product' => 'Cargador de batería', 'brand' => 'MAKITA', 'description' => 'DCR18RC - 18V, 3A', 'serial_number' => '22096158296', 'condition' => 'EN_REVISION', 'notes' => 'se perdió, en alianza', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'CGR-BTR-IN-06', 'product' => 'Cargador de batería', 'brand' => 'BOSCH', 'description' => 'GAL 1880 CV - 18V, 6A', 'serial_number' => '2607225935', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'CGR-BTR-07', 'product' => 'Cargador de batería', 'brand' => 'MAKITA', 'description' => 'DC18SD - 18V, 2.6A', 'serial_number' => '127175104 - 0717521', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'CGR-BTR-08', 'product' => 'Cargador de batería', 'brand' => 'MAKITA', 'description' => 'DC18SD - 18V, 2.6A', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'CMPRS-AIR-01', 'product' => 'Compresora de aire', 'brand' => 'MASUKI', 'description' => 'W-9 - 220v, 550w, 1680rpm, 9L', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'ESM-ANG-01', 'product' => 'Esmeril angular', 'brand' => 'MAKITA', 'description' => 'GA4530 - 220v, 3.3a, 720w, 11000rpm', 'serial_number' => '0558064', 'condition' => 'MALOGRADO', 'notes' => 'el gatillo no ajusta con protector de disco', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'ESM-ANG-02', 'product' => 'Esmeril angular', 'brand' => 'MAKITA', 'description' => 'GA4530 - 220v, 3.3a, 720w, 11000rpm', 'serial_number' => '00113451', 'condition' => 'BUENO', 'notes' => 'con protector de disco', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'ESM-ANG-03', 'product' => 'Esmeril angular', 'brand' => 'MAKITA', 'description' => 'GA4530 - 220v, 3.3a, 720w, 11000rpm', 'serial_number' => '00112755', 'condition' => 'BUENO', 'notes' => 'con protector de disco y mango rotito', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'ESM-ANG-04', 'product' => 'Esmeril angular', 'brand' => 'BOSCH', 'description' => 'GWS 9-125 S - 220v, 4.2a, 900w, 11000rpm', 'serial_number' => '023140193 2020', 'condition' => 'BUENO', 'notes' => 'con protector de disco y mango', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'ESM-IN-01', 'product' => 'Esmeril inalámbrico', 'brand' => 'BOSCH', 'description' => 'GWS 18V-10 - 18V', 'serial_number' => '23016263', 'condition' => 'BUENO', 'notes' => 'con protector de disco y mango', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'ESM-IN-02', 'product' => 'Esmeril inalámbrico', 'brand' => 'MAKITA', 'description' => 'M14 - 18V', 'serial_number' => '1772605', 'condition' => 'BUENO', 'notes' => 'con protector de disco y mango', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'HDRLV-01', 'product' => 'Hidrolavadora', 'brand' => 'KARCHER', 'description' => 'K3 550 - 220v, 8000w, 11.4kg', 'serial_number' => '015577', 'condition' => 'BUENO', 'notes' => 'con punta (522 078 0)', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'HDRLV-02', 'product' => 'Hidrolavadora', 'brand' => 'KARCHER', 'description' => 'K1 9.398 - 220v, 1200w, 4.6kg', 'serial_number' => '008287 2022', 'condition' => 'BUENO', 'notes' => 'con punta 360°', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'HDRLV-03', 'product' => 'Hidrolavadora', 'brand' => 'KARCHER', 'description' => 'K2 350 - 220v, 1400w, 5kg', 'serial_number' => '076449', 'condition' => 'BUENO', 'notes' => 'con punta 360° y punta larga', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'PSTL-CLR-01', 'product' => 'Pistola de calor', 'brand' => 'BAUKER', 'description' => 'HG250 - 220v, 2000w', 'serial_number' => '983495', 'condition' => 'BUENO', 'notes' => 'maletín con 4 accesorios', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'SRA-CRCLR-01', 'product' => 'Sierra circular', 'brand' => 'SKIL', 'description' => '5402 - 220v, 6.7a, 1400w, 6000rpm, 184mm', 'serial_number' => '032', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'SPLDR-01', 'product' => 'Soplador de aire', 'brand' => 'MAKITA', 'description' => 'MUB101 - 500W, 2.3A, 16000rpm', 'serial_number' => 'C0038621K', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'SPLDR-02', 'product' => 'Soplador de aire', 'brand' => 'DEWALT', 'description' => 'DWB800-B2C - 800W, 16000rpm', 'serial_number' => '10319', 'condition' => 'BUENO', 'notes' => 'No tiene punta de jebe, se perdió', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'SPLDR-03', 'product' => 'Soplador de aire', 'brand' => 'CROWN', 'description' => 'CT17010V - 710W, 3.08A, 14000rpm', 'serial_number' => '201005008 07', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'SPLDR-04', 'product' => 'Soplador de aire', 'brand' => 'BRIKER', 'description' => 'EB-BR080-42 - 800W, 16000rpm', 'serial_number' => '2107150360', 'condition' => 'MALOGRADO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'SPLDR-05', 'product' => 'Soplador de aire inalámbrico', 'brand' => 'MAKITA', 'description' => 'DUB185 - 18v, 3.2m3/min', 'serial_number' => '2023.3 - 215244k', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'SPLDR-06', 'product' => 'Soplador de aire', 'brand' => 'MAKITA', 'description' => 'M4000 - 220, 2.5A, 530W', 'serial_number' => '225093k - 2023.11', 'condition' => 'BUENO', 'notes' => 'tiene accesorio, una mini punta de jebe', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-IN-01', 'product' => 'Taladro inalámbrico', 'brand' => 'BOSCH', 'description' => 'GSB 18 VE-EC - 18V, 1.5Ah', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-IN-02', 'product' => 'Taladro inalámbrico', 'brand' => 'BOSCH', 'description' => 'GSB 18 VE-EC - 18V, 4.0Ah', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-IN-03', 'product' => 'Taladro inalámbrico', 'brand' => 'BOSCH', 'description' => 'GSR 1800 LI - 18V, 4.0Ah', 'serial_number' => null, 'condition' => 'REPARADO', 'notes' => 'tiene cinta roja', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-IN-04', 'product' => 'Taladro inalámbrico', 'brand' => 'BOSCH', 'description' => 'GSB 18V-150 C - bi turbo professional', 'serial_number' => '22600233', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-IN-05', 'product' => 'Taladro inalámbrico', 'brand' => 'DEWALT', 'description' => 'DCD996 - 20V, 4.0Ah', 'serial_number' => 'DHR1G4G', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-PRCT-01', 'product' => 'Taladro percutor', 'brand' => 'MAKITA', 'description' => 'M0801 - 220V, 2.4A, 500W', 'serial_number' => '00030371', 'condition' => 'BUENO', 'notes' => 'maletín bosch, enchufe menneke, S/LL-M', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-PRCT-02', 'product' => 'Taladro percutor', 'brand' => 'MAKITA', 'description' => 'MHP161 - 220V, 2.4A, 710W', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe monofásico, S/LL-M', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-PRCT-03', 'product' => 'Taladro percutor', 'brand' => 'MAKITA', 'description' => 'MHP161 - 220V, 2.4A, 710W', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe menneke, C/LL-M', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-PRCT-04', 'product' => 'Taladro percutor', 'brand' => 'MAKITA', 'description' => 'MHP160 - 220V, 710W', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe monofásico, C/LL-M', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-PRCT-05', 'product' => 'Taladro percutor', 'brand' => 'BOSCH', 'description' => 'GSB 16 RE - 220V, 3.4A, 750W', 'serial_number' => '802002793', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe monofásico, C/LL-M', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-PRCT-06', 'product' => 'Taladro percutor', 'brand' => 'BOSCH', 'description' => 'GSB 13 RE - 220V, 3.1A, 650W', 'serial_number' => '-', 'condition' => 'MALOGRADO', 'notes' => 'el gatillo para encender se atraca, maletín, enchufe monofásico, C/LL-M', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-PRCT-07', 'product' => 'Taladro percutor inalámbrico', 'brand' => 'BOSCH', 'description' => 'GBH 18V-26 - 220V, 6.0A', 'serial_number' => '221000240', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe monofásico', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-PRCT-08', 'product' => 'Taladro percutor inalámbrico', 'brand' => 'BOSCH', 'description' => 'GBH 18V-26 - 220V, 6.0A', 'serial_number' => '221000251', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe monofásico', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-ROTO-01', 'product' => 'Taladro rotomartillo', 'brand' => 'sin marca', 'description' => '220V', 'serial_number' => '-', 'condition' => 'MALOGRADO', 'notes' => 'quiere pero no enciende, maletín, enchufe monofásico, 3 puntas acople', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-ROTO-02', 'product' => 'Taladro rotomartillo', 'brand' => 'KAILI', 'description' => 'KP-068 - 230v, 1020w, 800rpm, 30mm', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe monofásico', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-ROTO-03', 'product' => 'Taladro rotomartillo', 'brand' => 'CROWN', 'description' => 'CT18003 - 220v, 1020w, 800rpm, 30mm', 'serial_number' => '11022400212', 'condition' => 'MALOGRADO', 'notes' => 'no enciende, maletín, enchufe menneke', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-ROTO-04', 'product' => 'Taladro rotomartillo', 'brand' => 'CROWN', 'description' => 'CT18003 - 220v, 1050w, 800rpm, 30mm', 'serial_number' => '13032900159', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe monofásico', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-ROTO-05', 'product' => 'Taladro rotomartillo', 'brand' => 'CROWN', 'description' => 'CT18003 - 220v, 1050w, 800rpm, 30mm', 'serial_number' => '13120300045', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe monofásico, con mango', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-ROTO-06', 'product' => 'Taladro rotomartillo', 'brand' => 'SAKI', 'description' => '220v, 15000w, 1400rpm, 65mm', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe monofásico, 2 puntas', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 2, 'code' => 'TLD-ROTO-07', 'product' => 'Taladro rotomartillo', 'brand' => 'BOSCH', 'description' => 'GBH 2-26 DRE - 220V, 3.9A, 800W, 900rpm, 26mm', 'serial_number' => '023000278', 'condition' => 'BUENO', 'notes' => 'maletín, enchufe monofásico, con mango', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],

            // 🪜 CATEGORÍA 3: Infraestructura y Elevación
            ['category_id' => 3, 'code' => 'ESCTJFV05-01', 'product' => 'Escalera de tijera', 'brand' => 'BULI AMERICAN LADDER', 'description' => 'FTD150-6IA - 6 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '1.80m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTJFV05-02', 'product' => 'Escalera de tijera', 'brand' => 'BULI AMERICAN LADDER', 'description' => 'FTD150-6IA - 6 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '1.80m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTJFV05-03', 'product' => 'Escalera de tijera', 'brand' => 'BULI AMERICAN LADDER', 'description' => 'FTD150-6IA - 6 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '1.80m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTJFV05-04', 'product' => 'Escalera de tijera', 'brand' => 'BULI AMERICAN LADDER', 'description' => 'FTD150-6IA - 6 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '1.80m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTJFV05-05', 'product' => 'Escalera de tijera', 'brand' => 'BULI AMERICAN LADDER', 'description' => 'FTD150-6IA - 6 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '1.80m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTJFB07-06', 'product' => 'Escalera de tijera', 'brand' => 'BULI AMERICAN LADDER', 'description' => 'FTD150-8IA - 8 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '2.40m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTJFB07-07', 'product' => 'Escalera de tijera', 'brand' => 'BULI AMERICAN LADDER', 'description' => 'FTD150-8IA - 8 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '2.40m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTJFB09-08', 'product' => 'Escalera de tijera', 'brand' => 'ESCALUMEX', 'description' => 'FTD-10 - 10 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '2.35M', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTLFB10-09', 'product' => 'Escalera telescópica', 'brand' => 'BULI AMERICAN LADDER', 'description' => '10 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => null, 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCPGFB08-10', 'product' => 'Escalera plegable', 'brand' => 'AMERICA VULCANO', 'description' => 'FM-8 - 9 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '2.7m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTJFB04-11', 'product' => 'Escalera de tijera', 'brand' => 'AMERICA VULCANO', 'description' => 'AFTD-5 - 5 pasos, fibra de vidrio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '1.50m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTJAL05-12', 'product' => 'Escalera de tijera', 'brand' => 'AMERICA VULCANO', 'description' => 'ATD-6 - 6 pasos, aluminio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '1.80m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 3, 'code' => 'ESCTJAL07-13', 'product' => 'Escalera de tijera', 'brand' => 'AMERICA VULCANO', 'description' => 'ATD-8 - 8 pasos, aluminio', 'serial_number' => '-', 'condition' => 'BUENO', 'notes' => '2.40m', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],

            // 🔩 CATEGORÍA 4: Conexiones y Tuberías
            ['category_id' => 4, 'code' => 'EXT-ADPT-01', 'product' => 'Extensión adaptador 2p', 'brand' => 'sin marca', 'description' => '1.40 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'menneke hembra & leviton macho, roto la tapa', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-ADPT-02', 'product' => 'Extensión adaptador 2p', 'brand' => 'sin marca', 'description' => '3.30 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'menneke macho & leviton hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-ADPT-03', 'product' => 'Extensión adaptador 2p', 'brand' => 'sin marca', 'description' => '0.70 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'menneke macho & leviton hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-ADPT-04', 'product' => 'Extensión adaptador 2p', 'brand' => 'sin marca', 'description' => '1.70 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'menneke hembra & leviton macho', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-ADPT-05', 'product' => 'Extensión adaptador 2p', 'brand' => 'sin marca', 'description' => '4.20 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'menneke macho & leviton hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-PNZ-06', 'product' => 'Extensión pinza 2p', 'brand' => 'sin marca', 'description' => '1.10 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton macho & pinza', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-PNZ-07', 'product' => 'Extensión pinza 2p', 'brand' => 'sin marca', 'description' => '0.70 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton hembra & pinza', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-AZL-08', 'product' => 'Extensión 3p azul', 'brand' => 'sin marca', 'description' => 'debajo de la mesa', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'meneeke macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-RJ-09', 'product' => 'Extensión 3p rojo', 'brand' => 'sin marca', 'description' => '8.00 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'meneeke macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-MH-10', 'product' => 'Extensión 2p M - H', 'brand' => 'sin marca', 'description' => '6.30 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-MH-11', 'product' => 'Extensión 2p M - H', 'brand' => 'sin marca', 'description' => '8.00 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-MH-12', 'product' => 'Extensión 2p M - H', 'brand' => 'sin marca', 'description' => '18.00 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-MH-13', 'product' => 'Extensión 2p M - H', 'brand' => 'sin marca', 'description' => '8.00 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-MH-14', 'product' => 'Extensión 2p M - H', 'brand' => 'sin marca', 'description' => '4.00 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-MH-15', 'product' => 'Extensión 2p M - H', 'brand' => 'sin marca', 'description' => '4.00 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-MH-16', 'product' => 'Extensión 2p M - H', 'brand' => 'sin marca', 'description' => '6.00 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-MH-17', 'product' => 'Extensión 2p M - H', 'brand' => 'sin marca', 'description' => '11.00 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'EXT-MH-18', 'product' => 'Extensión 2p M - H', 'brand' => 'sin marca', 'description' => '19.00 metros', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'leviton macho & hembra', 'stock' => null, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'ABRZ-1OR', 'product' => 'Abrazadera - una oreja', 'brand' => '-', 'description' => '3/4" luz & 1/2" agua (100pcs)', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'BOLSAS. Entrada: 2023-12-01, Salida: 2023-12-27', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'ABRZ-1OR-02', 'product' => 'Abrazadera - una oreja', 'brand' => '-', 'description' => '1-1/2" luz & 1-1/4" agua (100pcs)', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'BOLSAS. Entrada: 2023-12-01', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'ABRZ-1OR-03', 'product' => 'Abrazadera - una oreja', 'brand' => '-', 'description' => '2" luz & 1-1/2" agua (50pcs)', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'BOLSAS. Entrada: 2023-12-01', 'stock' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'ABRZ-UNST', 'product' => 'Abrazadera - unistrut', 'brand' => 'CULUS', 'description' => '1"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 13, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'ADPT-REFR', 'product' => 'Adaptador de refrigerante', 'brand' => 'CPS', 'description' => 'r410a', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 3, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'ADPT-MAG-01', 'product' => 'Adaptador magnético', 'brand' => 'TRUPER', 'description' => 'para punteras 100mm', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 5, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'ADPT-MAG-02', 'product' => 'Adaptador magnético', 'brand' => 'TRUPER', 'description' => 'para punteras 60mm', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 11, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-FLX', 'product' => 'Tubo flexible', 'brand' => '-', 'description' => '3/8"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'ROLLO. Entrada: 2023-12-01', 'stock' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-45-01', 'product' => 'Tubo PVC - 45°', 'brand' => '-', 'description' => '1/2"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 2, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-45-02', 'product' => 'Tubo PVC - 45°', 'brand' => '-', 'description' => '3/4"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 4, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-CD-01', 'product' => 'Tubo PVC - codo agua', 'brand' => '-', 'description' => '1/2"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 54, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-CD-02', 'product' => 'Tubo PVC - codo agua', 'brand' => '-', 'description' => '3/4"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 145, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-CD-03', 'product' => 'Tubo PVC - codo agua', 'brand' => 'PAVCO', 'description' => '3/4"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 15, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-CD-04', 'product' => 'Tubo PVC - codo agua caliente', 'brand' => '-', 'description' => '1/2"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 16, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-CRV-01', 'product' => 'Tubo PVC - curva luz', 'brand' => '-', 'description' => '1/2"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 63, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-CRV-02', 'product' => 'Tubo PVC - curva luz', 'brand' => '-', 'description' => '3/4"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 10, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-RDC', 'product' => 'Tubo PVC - reducción agua', 'brand' => '-', 'description' => '3/4" a 1/2"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 70, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-TE-01', 'product' => 'Tubo PVC - te agua', 'brand' => '-', 'description' => '1/2"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 45, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 4, 'code' => 'TUB-PVC-TE-02', 'product' => 'Tubo PVC - te agua', 'brand' => '-', 'description' => '3/4"', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 50, 'created_at' => now(), 'updated_at' => now()],

            // 📦 CATEGORÍA 5: Insumos y Lubricantes
            ['category_id' => 5, 'code' => 'ACT-LUB', 'product' => 'Aceite lubricante', 'brand' => 'TRUPER', 'description' => '90ml', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 12, 'created_at' => now(), 'updated_at' => now()],
            ['category_id' => 5, 'code' => 'ACT-BMB-CND', 'product' => 'Aceite para bomba conden.', 'brand' => 'CPS', 'description' => '32oz', 'serial_number' => null, 'condition' => 'BUENO', 'notes' => 'UNITARIO. Entrada: 2023-12-01', 'stock' => 1, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
